module Godot.Core.GodotSliderJoint where
import Data.Coerce
import Foreign.C
import Godot.Internal.Dispatch
import System.IO.Unsafe
import Godot.Gdnative.Internal
import Godot.Gdnative.Types
import Godot.Api

pattern PARAM_ANGULAR_LIMIT_LOWER :: Int

pattern PARAM_ANGULAR_LIMIT_LOWER = 12

pattern PARAM_LINEAR_ORTHOGONAL_RESTITUTION :: Int

pattern PARAM_LINEAR_ORTHOGONAL_RESTITUTION = 9

pattern PARAM_ANGULAR_MOTION_DAMPING :: Int

pattern PARAM_ANGULAR_MOTION_DAMPING = 18

pattern PARAM_LINEAR_LIMIT_RESTITUTION :: Int

pattern PARAM_LINEAR_LIMIT_RESTITUTION = 3

pattern PARAM_LINEAR_MOTION_RESTITUTION :: Int

pattern PARAM_LINEAR_MOTION_RESTITUTION = 6

pattern PARAM_ANGULAR_ORTHOGONAL_DAMPING :: Int

pattern PARAM_ANGULAR_ORTHOGONAL_DAMPING = 21

pattern PARAM_ANGULAR_ORTHOGONAL_SOFTNESS :: Int

pattern PARAM_ANGULAR_ORTHOGONAL_SOFTNESS = 19

pattern PARAM_LINEAR_ORTHOGONAL_SOFTNESS :: Int

pattern PARAM_LINEAR_ORTHOGONAL_SOFTNESS = 8

pattern PARAM_LINEAR_LIMIT_SOFTNESS :: Int

pattern PARAM_LINEAR_LIMIT_SOFTNESS = 2

pattern PARAM_ANGULAR_LIMIT_RESTITUTION :: Int

pattern PARAM_ANGULAR_LIMIT_RESTITUTION = 14

pattern PARAM_LINEAR_LIMIT_LOWER :: Int

pattern PARAM_LINEAR_LIMIT_LOWER = 1

pattern PARAM_LINEAR_MOTION_SOFTNESS :: Int

pattern PARAM_LINEAR_MOTION_SOFTNESS = 5

pattern PARAM_MAX :: Int

pattern PARAM_MAX = 22

pattern PARAM_ANGULAR_LIMIT_DAMPING :: Int

pattern PARAM_ANGULAR_LIMIT_DAMPING = 15

pattern PARAM_ANGULAR_LIMIT_SOFTNESS :: Int

pattern PARAM_ANGULAR_LIMIT_SOFTNESS = 13

pattern PARAM_LINEAR_LIMIT_UPPER :: Int

pattern PARAM_LINEAR_LIMIT_UPPER = 0

pattern PARAM_ANGULAR_LIMIT_UPPER :: Int

pattern PARAM_ANGULAR_LIMIT_UPPER = 11

pattern PARAM_LINEAR_LIMIT_DAMPING :: Int

pattern PARAM_LINEAR_LIMIT_DAMPING = 4

pattern PARAM_ANGULAR_MOTION_RESTITUTION :: Int

pattern PARAM_ANGULAR_MOTION_RESTITUTION = 17

pattern PARAM_LINEAR_ORTHOGONAL_DAMPING :: Int

pattern PARAM_LINEAR_ORTHOGONAL_DAMPING = 10

pattern PARAM_ANGULAR_ORTHOGONAL_RESTITUTION :: Int

pattern PARAM_ANGULAR_ORTHOGONAL_RESTITUTION = 20

pattern PARAM_LINEAR_MOTION_DAMPING :: Int

pattern PARAM_LINEAR_MOTION_DAMPING = 7

pattern PARAM_ANGULAR_MOTION_SOFTNESS :: Int

pattern PARAM_ANGULAR_MOTION_SOFTNESS = 16