module Godot.Core.GodotNavigationMesh where
import Data.Coerce
import Foreign.C
import Godot.Internal.Dispatch
import System.IO.Unsafe
import Godot.Gdnative.Internal
import Godot.Gdnative.Types
import Godot.Api.Auto

pattern SAMPLE_PARTITION_MAX :: Int

pattern SAMPLE_PARTITION_MAX = 3

pattern SAMPLE_PARTITION_WATERSHED :: Int

pattern SAMPLE_PARTITION_WATERSHED = 0

pattern SAMPLE_PARTITION_LAYERS :: Int

pattern SAMPLE_PARTITION_LAYERS = 2

pattern SOURCE_GEOMETRY_MAX :: Int

pattern SOURCE_GEOMETRY_MAX = 3

pattern SOURCE_GEOMETRY_GROUPS_EXPLICIT :: Int

pattern SOURCE_GEOMETRY_GROUPS_EXPLICIT = 2

pattern PARSED_GEOMETRY_BOTH :: Int

pattern PARSED_GEOMETRY_BOTH = 2

pattern SOURCE_GEOMETRY_NAVMESH_CHILDREN :: Int

pattern SOURCE_GEOMETRY_NAVMESH_CHILDREN = 0

pattern PARSED_GEOMETRY_STATIC_COLLIDERS :: Int

pattern PARSED_GEOMETRY_STATIC_COLLIDERS = 1

pattern SAMPLE_PARTITION_MONOTONE :: Int

pattern SAMPLE_PARTITION_MONOTONE = 1

pattern SOURCE_GEOMETRY_GROUPS_WITH_CHILDREN :: Int

pattern SOURCE_GEOMETRY_GROUPS_WITH_CHILDREN = 1

pattern PARSED_GEOMETRY_MAX :: Int

pattern PARSED_GEOMETRY_MAX = 3

pattern PARSED_GEOMETRY_MESH_INSTANCES :: Int

pattern PARSED_GEOMETRY_MESH_INSTANCES = 0