module Godot.Core.GodotPerformance where
import Data.Coerce
import Foreign.C
import Godot.Internal.Dispatch
import System.IO.Unsafe
import Godot.Gdnative.Internal
import Godot.Gdnative.Types
import Godot.Api.Auto

pattern PHYSICS_2D_ISLAND_COUNT :: Int

pattern PHYSICS_2D_ISLAND_COUNT = 23

pattern OBJECT_RESOURCE_COUNT :: Int

pattern OBJECT_RESOURCE_COUNT = 9

pattern RENDER_VERTEX_MEM_USED :: Int

pattern RENDER_VERTEX_MEM_USED = 19

pattern PHYSICS_3D_ISLAND_COUNT :: Int

pattern PHYSICS_3D_ISLAND_COUNT = 26

pattern PHYSICS_2D_COLLISION_PAIRS :: Int

pattern PHYSICS_2D_COLLISION_PAIRS = 22

pattern MEMORY_STATIC_MAX :: Int

pattern MEMORY_STATIC_MAX = 5

pattern TIME_PHYSICS_PROCESS :: Int

pattern TIME_PHYSICS_PROCESS = 2

pattern RENDER_TEXTURE_MEM_USED :: Int

pattern RENDER_TEXTURE_MEM_USED = 18

pattern MEMORY_DYNAMIC_MAX :: Int

pattern MEMORY_DYNAMIC_MAX = 6

pattern MEMORY_DYNAMIC :: Int

pattern MEMORY_DYNAMIC = 4

pattern RENDER_MATERIAL_CHANGES_IN_FRAME :: Int

pattern RENDER_MATERIAL_CHANGES_IN_FRAME = 13

pattern OBJECT_NODE_COUNT :: Int

pattern OBJECT_NODE_COUNT = 10

pattern AUDIO_OUTPUT_LATENCY :: Int

pattern AUDIO_OUTPUT_LATENCY = 27

pattern RENDER_OBJECTS_IN_FRAME :: Int

pattern RENDER_OBJECTS_IN_FRAME = 11

pattern RENDER_DRAW_CALLS_IN_FRAME :: Int

pattern RENDER_DRAW_CALLS_IN_FRAME = 16

pattern TIME_PROCESS :: Int

pattern TIME_PROCESS = 1

pattern MEMORY_MESSAGE_BUFFER_MAX :: Int

pattern MEMORY_MESSAGE_BUFFER_MAX = 7

pattern PHYSICS_3D_COLLISION_PAIRS :: Int

pattern PHYSICS_3D_COLLISION_PAIRS = 25

pattern RENDER_SHADER_CHANGES_IN_FRAME :: Int

pattern RENDER_SHADER_CHANGES_IN_FRAME = 14

pattern MONITOR_MAX :: Int

pattern MONITOR_MAX = 28

pattern TIME_FPS :: Int

pattern TIME_FPS = 0

pattern PHYSICS_2D_ACTIVE_OBJECTS :: Int

pattern PHYSICS_2D_ACTIVE_OBJECTS = 21

pattern RENDER_SURFACE_CHANGES_IN_FRAME :: Int

pattern RENDER_SURFACE_CHANGES_IN_FRAME = 15

pattern RENDER_VIDEO_MEM_USED :: Int

pattern RENDER_VIDEO_MEM_USED = 17

pattern MEMORY_STATIC :: Int

pattern MEMORY_STATIC = 3

pattern RENDER_VERTICES_IN_FRAME :: Int

pattern RENDER_VERTICES_IN_FRAME = 12

pattern OBJECT_COUNT :: Int

pattern OBJECT_COUNT = 8

pattern PHYSICS_3D_ACTIVE_OBJECTS :: Int

pattern PHYSICS_3D_ACTIVE_OBJECTS = 24

pattern RENDER_USAGE_VIDEO_MEM_TOTAL :: Int

pattern RENDER_USAGE_VIDEO_MEM_TOTAL = 20