module Godot.Core.GodotPerformance where
import Data.Coerce
import Foreign.C
import Godot.Internal.Dispatch
import System.IO.Unsafe
import Godot.Gdnative.Internal
import Godot.Gdnative.Types
import Godot.Api.Auto

pattern PHYSICS_3D_ACTIVE_OBJECTS :: Int

pattern PHYSICS_3D_ACTIVE_OBJECTS = 27

pattern OBJECT_ORPHAN_NODE_COUNT :: Int

pattern OBJECT_ORPHAN_NODE_COUNT = 11

pattern OBJECT_RESOURCE_COUNT :: Int

pattern OBJECT_RESOURCE_COUNT = 9

pattern RENDER_VIDEO_MEM_USED :: Int

pattern RENDER_VIDEO_MEM_USED = 20

pattern RENDER_TEXTURE_MEM_USED :: Int

pattern RENDER_TEXTURE_MEM_USED = 21

pattern RENDER_SURFACE_CHANGES_IN_FRAME :: Int

pattern RENDER_SURFACE_CHANGES_IN_FRAME = 16

pattern OBJECT_COUNT :: Int

pattern OBJECT_COUNT = 8

pattern MEMORY_MESSAGE_BUFFER_MAX :: Int

pattern MEMORY_MESSAGE_BUFFER_MAX = 7

pattern MONITOR_MAX :: Int

pattern MONITOR_MAX = 31

pattern RENDER_OBJECTS_IN_FRAME :: Int

pattern RENDER_OBJECTS_IN_FRAME = 12

pattern PHYSICS_2D_ISLAND_COUNT :: Int

pattern PHYSICS_2D_ISLAND_COUNT = 26

pattern OBJECT_NODE_COUNT :: Int

pattern OBJECT_NODE_COUNT = 10

pattern MEMORY_DYNAMIC_MAX :: Int

pattern MEMORY_DYNAMIC_MAX = 6

pattern RENDER_SHADER_CHANGES_IN_FRAME :: Int

pattern RENDER_SHADER_CHANGES_IN_FRAME = 15

pattern PHYSICS_2D_ACTIVE_OBJECTS :: Int

pattern PHYSICS_2D_ACTIVE_OBJECTS = 24

pattern PHYSICS_2D_COLLISION_PAIRS :: Int

pattern PHYSICS_2D_COLLISION_PAIRS = 25

pattern MEMORY_DYNAMIC :: Int

pattern MEMORY_DYNAMIC = 4

pattern MEMORY_STATIC :: Int

pattern MEMORY_STATIC = 3

pattern TIME_PROCESS :: Int

pattern TIME_PROCESS = 1

pattern RENDER_VERTICES_IN_FRAME :: Int

pattern RENDER_VERTICES_IN_FRAME = 13

pattern RENDER_MATERIAL_CHANGES_IN_FRAME :: Int

pattern RENDER_MATERIAL_CHANGES_IN_FRAME = 14

pattern RENDER_DRAW_CALLS_IN_FRAME :: Int

pattern RENDER_DRAW_CALLS_IN_FRAME = 17

pattern MEMORY_STATIC_MAX :: Int

pattern MEMORY_STATIC_MAX = 5

pattern TIME_FPS :: Int

pattern TIME_FPS = 0

pattern RENDER_2D_ITEMS_IN_FRAME :: Int

pattern RENDER_2D_ITEMS_IN_FRAME = 18

pattern RENDER_USAGE_VIDEO_MEM_TOTAL :: Int

pattern RENDER_USAGE_VIDEO_MEM_TOTAL = 23

pattern AUDIO_OUTPUT_LATENCY :: Int

pattern AUDIO_OUTPUT_LATENCY = 30

pattern PHYSICS_3D_COLLISION_PAIRS :: Int

pattern PHYSICS_3D_COLLISION_PAIRS = 28

pattern RENDER_2D_DRAW_CALLS_IN_FRAME :: Int

pattern RENDER_2D_DRAW_CALLS_IN_FRAME = 19

pattern RENDER_VERTEX_MEM_USED :: Int

pattern RENDER_VERTEX_MEM_USED = 22

pattern TIME_PHYSICS_PROCESS :: Int

pattern TIME_PHYSICS_PROCESS = 2

pattern PHYSICS_3D_ISLAND_COUNT :: Int

pattern PHYSICS_3D_ISLAND_COUNT = 29