module Godot.Core.GodotGeneric6DOFJoint where
import Data.Coerce
import Foreign.C
import Godot.Internal.Dispatch
import System.IO.Unsafe
import Godot.Gdnative.Internal
import Godot.Gdnative.Types
import Godot.Api.Auto

pattern PARAM_ANGULAR_FORCE_LIMIT :: Int

pattern PARAM_ANGULAR_FORCE_LIMIT = 15

pattern PARAM_ANGULAR_ERP :: Int

pattern PARAM_ANGULAR_ERP = 16

pattern PARAM_ANGULAR_RESTITUTION :: Int

pattern PARAM_ANGULAR_RESTITUTION = 14

pattern PARAM_LINEAR_LOWER_LIMIT :: Int

pattern PARAM_LINEAR_LOWER_LIMIT = 0

pattern PARAM_MAX :: Int

pattern PARAM_MAX = 22

pattern PARAM_LINEAR_LIMIT_SOFTNESS :: Int

pattern PARAM_LINEAR_LIMIT_SOFTNESS = 2

pattern FLAG_ENABLE_MOTOR :: Int

pattern FLAG_ENABLE_MOTOR = 4

pattern FLAG_MAX :: Int

pattern FLAG_MAX = 6

pattern PARAM_LINEAR_MOTOR_FORCE_LIMIT :: Int

pattern PARAM_LINEAR_MOTOR_FORCE_LIMIT = 6

pattern PARAM_ANGULAR_SPRING_STIFFNESS :: Int

pattern PARAM_ANGULAR_SPRING_STIFFNESS = 19

pattern PARAM_ANGULAR_DAMPING :: Int

pattern PARAM_ANGULAR_DAMPING = 13

pattern PARAM_LINEAR_DAMPING :: Int

pattern PARAM_LINEAR_DAMPING = 4

pattern PARAM_ANGULAR_MOTOR_FORCE_LIMIT :: Int

pattern PARAM_ANGULAR_MOTOR_FORCE_LIMIT = 18

pattern PARAM_ANGULAR_MOTOR_TARGET_VELOCITY :: Int

pattern PARAM_ANGULAR_MOTOR_TARGET_VELOCITY = 17

pattern FLAG_ENABLE_LINEAR_LIMIT :: Int

pattern FLAG_ENABLE_LINEAR_LIMIT = 0

pattern PARAM_ANGULAR_SPRING_DAMPING :: Int

pattern PARAM_ANGULAR_SPRING_DAMPING = 20

pattern PARAM_LINEAR_SPRING_EQUILIBRIUM_POINT :: Int

pattern PARAM_LINEAR_SPRING_EQUILIBRIUM_POINT = 9

pattern FLAG_ENABLE_ANGULAR_SPRING :: Int

pattern FLAG_ENABLE_ANGULAR_SPRING = 2

pattern FLAG_ENABLE_LINEAR_MOTOR :: Int

pattern FLAG_ENABLE_LINEAR_MOTOR = 5

pattern PARAM_ANGULAR_UPPER_LIMIT :: Int

pattern PARAM_ANGULAR_UPPER_LIMIT = 11

pattern PARAM_ANGULAR_SPRING_EQUILIBRIUM_POINT :: Int

pattern PARAM_ANGULAR_SPRING_EQUILIBRIUM_POINT = 21

pattern PARAM_LINEAR_MOTOR_TARGET_VELOCITY :: Int

pattern PARAM_LINEAR_MOTOR_TARGET_VELOCITY = 5

pattern PARAM_LINEAR_SPRING_DAMPING :: Int

pattern PARAM_LINEAR_SPRING_DAMPING = 8

pattern PARAM_LINEAR_RESTITUTION :: Int

pattern PARAM_LINEAR_RESTITUTION = 3

pattern PARAM_ANGULAR_LIMIT_SOFTNESS :: Int

pattern PARAM_ANGULAR_LIMIT_SOFTNESS = 12

pattern PARAM_ANGULAR_LOWER_LIMIT :: Int

pattern PARAM_ANGULAR_LOWER_LIMIT = 10

pattern FLAG_ENABLE_LINEAR_SPRING :: Int

pattern FLAG_ENABLE_LINEAR_SPRING = 3

pattern PARAM_LINEAR_UPPER_LIMIT :: Int

pattern PARAM_LINEAR_UPPER_LIMIT = 1

pattern PARAM_LINEAR_SPRING_STIFFNESS :: Int

pattern PARAM_LINEAR_SPRING_STIFFNESS = 7

pattern FLAG_ENABLE_ANGULAR_LIMIT :: Int

pattern FLAG_ENABLE_ANGULAR_LIMIT = 1