name: godot-haskell
synopsis: Haskell bindings for the Godot game engine API
description: This package contains Haskell bindings for GDNative and the Godot API. For details and examples, see README.md
version: '3.1.0.0'
category: Web
author: David Kraeutmann
maintainer: kane@kane.cx
copyright: 2018 David Kraeutmann
license: BSD3
github: KaneTW/godot-haskell
extra-source-files:
- README.md
- cbits/*
- godot_headers/**/*.h
- godot_headers/**/*.json

dependencies:
- base
- aeson
- bytestring
- template-haskell
- th-abstraction
- lens
- text
- casing
- vector
- containers
- unordered-containers
- mtl
- stm
- extra

default-extensions:
- FlexibleContexts
- FlexibleInstances
- ScopedTypeVariables
- TypeApplications
- StandaloneDeriving
- DerivingStrategies
- DefaultSignatures
- MultiParamTypeClasses
- FunctionalDependencies
- TypeFamilies
- TemplateHaskell
- TypeOperators
- TypeInType
- QuasiQuotes
- OverloadedStrings
- PatternSynonyms
- GeneralizedNewtypeDeriving

library:
  source-dirs: src
  generated-other-modules: Paths_godot_haskell
  build-tools:
  - c2hs
  include-dirs:
  - godot_headers
  - cbits
  dependencies:
  - generate
  - linear
  - colour

internal-libraries:
  generate:
    source-dirs: src-generate
    dependencies:
    - parsec
    - parsers
    - mtl
    - ansi-wl-pprint
