-- | This file is AUTOGENERATED by godot-haskell-project-generator. DO NOT EDIT

module Project.Requirements where
import Project.Support

type Nodes = '[OneResourceNode "Bullet" "Bullet", OneResourceNode "Enemy" "Enemy", OneResourceNode "Player" "Player"]
