-- | This file is AUTOGENERATED by godot-haskell-project-generator. DO NOT EDIT

module Project.Requirements where
import Project.Support

type Nodes = '[OneResourceNode "HUD" "HUD", OneResourceNode "Main" "Main", OneResourceNode "Mob" "Mob", OneResourceNode "Player" "Player"]
