resolver: nightly-2019-04-09

packages:
- .

# Using a specific revision:
extra-deps:
- ../../

require-stack-version: ">=1.8"

nix:
  enable: false
  pure: true
  packages: []
  shell-file: stack-shell.nix
  nix-shell-options: []
  path: []
  add-gc-roots: false


