name: myproject
version: '0.0.0.0'
description: Please see the README on Github at <https://github.com/abarbu/myproject#readme>
author: Andrei Barbu
maintainer: andrei@0xab.com
copyright: Andrei Barbu 2019
license: BSD3
github: abarbu/myproject
extra-source-files:
- ChangeLog.md
- README.md
dependencies:
- base >=4.12 && <5
- godot-haskell
- linear
- random
- deepseq
- text
- vector
- strict-concurrency
- lens
- template-haskell
- th-abstraction
- containers
- extra
library:
  source-dirs:
    - src
    - game
  exposed-modules:
  - Lib

verbatim: |
  foreign-library myproject
    type: native-shared
    other-modules: FLib
    hs-source-dirs: ffi/flib
    c-sources: ffi/cbits/flib.c
    build-depends:
        base >= 4.12 && <5
      , godot-haskell
      , myproject
      , text
    default-language: Haskell2010
