-- | This file is AUTOGENERATED by godot-haskell-project-generator. DO NOT EDIT

{-# LANGUAGE FlexibleContexts, FunctionalDependencies, MultiParamTypeClasses,
  UndecidableInstances, OverloadedStrings, TemplateHaskell, TypeApplications,
  TypeFamilies, DataKinds, TypeOperators, FlexibleInstances, RankNTypes,
  AllowAmbiguousTypes, ScopedTypeVariables, DerivingStrategies,
  GeneralizedNewtypeDeriving, LambdaCase #-}

module Project.Scenes.Bullet where
import Project.Support
import Godot
import GHC.TypeLits

import Godot.Core.AnimationPlayer()
import Godot.Core.RigidBody2D()
import Godot.Core.CollisionShape2D()
import Godot.Core.Sprite()

instance SceneResourcePath "Bullet" where
  sceneResourcePath = "res://Bullet.tscn"


instance SceneRoot "Bullet" where
  type SceneRootNode "Bullet" = "Bullet"


instance SceneNode        "Bullet" "AnimationPlayer" where
  type SceneNodeType      "Bullet" "AnimationPlayer" = AnimationPlayer
  type SceneNodeName      "Bullet" "AnimationPlayer" = "AnimationPlayer"
  type SceneNodeIsHaskell "Bullet" "AnimationPlayer" = 'Nothing


instance SceneNode        "Bullet" "Bullet" where
  type SceneNodeType      "Bullet" "Bullet" = RigidBody2D
  type SceneNodeName      "Bullet" "Bullet" = "Bullet"
  type SceneNodeIsHaskell "Bullet" "Bullet" = 'Just '("Bullet", "Bullet")


instance SceneNode        "Bullet" "CollisionShape2D" where
  type SceneNodeType      "Bullet" "CollisionShape2D" = CollisionShape2D
  type SceneNodeName      "Bullet" "CollisionShape2D" = "CollisionShape2D"
  type SceneNodeIsHaskell "Bullet" "CollisionShape2D" = 'Nothing


instance SceneNode        "Bullet" "Sprite" where
  type SceneNodeType      "Bullet" "Sprite" = Sprite
  type SceneNodeName      "Bullet" "Sprite" = "Sprite"
  type SceneNodeIsHaskell "Bullet" "Sprite" = 'Nothing


instance SceneConnection "Bullet" "AnimationPlayer" "animation_finished" "Bullet" "_on_AnimationPlayer_animation_finished"


instance SceneConnection "Bullet" "Bullet" "body_entered" "Bullet" "_on_Bullet_body_entered"

