-- | This file is AUTOGENERATED by godot-haskell-project-generator. DO NOT EDIT

{-# LANGUAGE FlexibleContexts, FunctionalDependencies, MultiParamTypeClasses,
  UndecidableInstances, OverloadedStrings, TemplateHaskell, TypeApplications,
  TypeFamilies, DataKinds, TypeOperators, FlexibleInstances, RankNTypes,
  AllowAmbiguousTypes, ScopedTypeVariables, DerivingStrategies,
  GeneralizedNewtypeDeriving, LambdaCase #-}

module Project.Scenes.Explosion where
import Project.Support
import Godot
import GHC.TypeLits

import Godot.Core.Particles2D()

instance SceneResourcePath "Explosion" where
  sceneResourcePath = "res://Explosion.tscn"


instance SceneRoot "Explosion" where
  type SceneRootNode "Explosion" = "Particles2D"


instance SceneNode        "Explosion" "Particles2D" where
  type SceneNodeType      "Explosion" "Particles2D" = Particles2D
  type SceneNodeName      "Explosion" "Particles2D" = "Particles2D"
  type SceneNodeIsHaskell "Explosion" "Particles2D" = 'Nothing

